### ISSUE TITLE
Hello，How can I obtain the dataset of this competition?

### ISSUE THREAD

**Issue by Jellyyoung** [alexeygrigorev/unpossibly-instagram-challenge#1]
hello，I want to review this competition，but I have no access to get the dataset，so I ask you for help...
my email is yangyd@seu.edu.cn，thank you！

**Comment by alexeygrigorev** [comment]
Hi, I'm not sure I'm supposed to distribute the dataset. I think it's best if you ask the organizers - check their contacts at unpossibly.com.au
